language: python
python:
 - 3.6

sudo: required
services:
  - docker

cache: pip

addons:
  apt:
    packages:
      - libssl-dev
      - python3-dev

before_script:
  - pip install coala-bears
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - sed -i.bak '/bears = GitCommitBear/d' .coafile
  - coala --non-interactive -V
  - python -m pytest
  - docker build -t "corobo" .
  - docker images
  - >
    docker run --user root corobo /bin/sh -c "
        set -e -x
        pip install -r test-requirements.txt;
        find -name \"**.pyc\" -delete;
        python -m pytest
    "
  - codecov

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c15f764f44886af1cf87
    on_success: never
    on_failure: always
